package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer id;
	private String codigo;
	private String empresa;
	private String contacto;
	private String cargoContacto;
	private String direccion;
	private String ciudad;
	private String region;
	private String cp;
	private String pais;
	private String telefono;
	private String fax;
	private Set pedidoses = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String codigo, String empresa) {
		this.codigo = codigo;
		this.empresa = empresa;
	}

	
	@Override
	public String toString() {
		return "Clientes [codigo=" + codigo + ", empresa=" + empresa + ", contacto=" + contacto + ", cargoContacto="
				+ cargoContacto + "]";
	}

	public Clientes(String codigo, String empresa, String contacto, String cargoContacto, String direccion,
			String ciudad, String region, String cp, String pais, String telefono, String fax, Set pedidoses) {
		this.codigo = codigo;
		this.empresa = empresa;
		this.contacto = contacto;
		this.cargoContacto = cargoContacto;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.region = region;
		this.cp = cp;
		this.pais = pais;
		this.telefono = telefono;
		this.fax = fax;
		this.pedidoses = pedidoses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public String getCargoContacto() {
		return this.cargoContacto;
	}

	public void setCargoContacto(String cargoContacto) {
		this.cargoContacto = cargoContacto;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

}
