package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;

/**
 * Detalles generated by hbm2java
 */
public class Detalles implements java.io.Serializable {

	private DetallesId id;
	private Pedidos pedidos;
	private Productos productos;
	private BigDecimal precioUnidad;
	private Short cantidad;
	private Double descuento;

	public Detalles() {
	}

	public Detalles(DetallesId id, Pedidos pedidos, Productos productos) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
	}

	public Detalles(DetallesId id, Pedidos pedidos, Productos productos, BigDecimal precioUnidad, Short cantidad,
			Double descuento) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
		this.precioUnidad = precioUnidad;
		this.cantidad = cantidad;
		this.descuento = descuento;
	}

	public DetallesId getId() {
		return this.id;
	}

	public void setId(DetallesId id) {
		this.id = id;
	}

	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}

}
