package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Envios generated by hbm2java
 */
public class Envios implements java.io.Serializable {

	private Integer id;
	private String empresa;
	private String telefono;
	private Set pedidoses = new HashSet(0);

	public Envios() {
	}

	public Envios(String empresa) {
		this.empresa = empresa;
	}

	public Envios(String empresa, String telefono, Set pedidoses) {
		this.empresa = empresa;
		this.telefono = telefono;
		this.pedidoses = pedidoses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

}
