package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

/**
 * Importes generated by hbm2java
 */
public class Importes implements java.io.Serializable {

	private ImportesId id;

	public Importes() {
	}

	public Importes(ImportesId id) {
		this.id = id;
	}

	public ImportesId getId() {
		return this.id;
	}

	public void setId(ImportesId id) {
		this.id = id;
	}

}
