package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos implements java.io.Serializable {

	private Integer id;
	private Clientes clientes;
	private Empleados empleados;
	private Envios envios;
	private Date fechaPedido;
	private Date fechaEntrega;
	private Date fechaEnvio;
	private BigDecimal cargo;
	private String destinatario;
	private String direccionDestinatario;
	private String ciudadDestinatario;
	private String regionDestinatario;
	private String cpDestinatario;
	private String paisDestinatario;
	private Set detalleses = new HashSet(0);

	public Pedidos() {
	}

	public Pedidos(Clientes clientes) {
		this.clientes = clientes;
	}

	public Pedidos(Clientes clientes, Empleados empleados, Envios envios, Date fechaPedido, Date fechaEntrega,
			Date fechaEnvio, BigDecimal cargo, String destinatario, String direccionDestinatario,
			String ciudadDestinatario, String regionDestinatario, String cpDestinatario, String paisDestinatario,
			Set detalleses) {
		this.clientes = clientes;
		this.empleados = empleados;
		this.envios = envios;
		this.fechaPedido = fechaPedido;
		this.fechaEntrega = fechaEntrega;
		this.fechaEnvio = fechaEnvio;
		this.cargo = cargo;
		this.destinatario = destinatario;
		this.direccionDestinatario = direccionDestinatario;
		this.ciudadDestinatario = ciudadDestinatario;
		this.regionDestinatario = regionDestinatario;
		this.cpDestinatario = cpDestinatario;
		this.paisDestinatario = paisDestinatario;
		this.detalleses = detalleses;
	}

	@Override
	public String toString() {
		return "Pedidos [id=" + id + ", fechaPedido=" + fechaPedido + ", fechaEntrega=" + fechaEntrega + ", fechaEnvio="
				+ fechaEnvio + ", cargo=" + cargo + ", destinatario=" + destinatario + ", direccionDestinatario="
				+ direccionDestinatario + ", ciudadDestinatario=" + ciudadDestinatario + ", regionDestinatario="
				+ regionDestinatario + ", cpDestinatario=" + cpDestinatario + ", paisDestinatario=" + paisDestinatario
				+ "]";
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Envios getEnvios() {
		return this.envios;
	}

	public void setEnvios(Envios envios) {
		this.envios = envios;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public BigDecimal getCargo() {
		return this.cargo;
	}

	public void setCargo(BigDecimal cargo) {
		this.cargo = cargo;
	}

	public String getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

	public String getDireccionDestinatario() {
		return this.direccionDestinatario;
	}

	public void setDireccionDestinatario(String direccionDestinatario) {
		this.direccionDestinatario = direccionDestinatario;
	}

	public String getCiudadDestinatario() {
		return this.ciudadDestinatario;
	}

	public void setCiudadDestinatario(String ciudadDestinatario) {
		this.ciudadDestinatario = ciudadDestinatario;
	}

	public String getRegionDestinatario() {
		return this.regionDestinatario;
	}

	public void setRegionDestinatario(String regionDestinatario) {
		this.regionDestinatario = regionDestinatario;
	}

	public String getCpDestinatario() {
		return this.cpDestinatario;
	}

	public void setCpDestinatario(String cpDestinatario) {
		this.cpDestinatario = cpDestinatario;
	}

	public String getPaisDestinatario() {
		return this.paisDestinatario;
	}

	public void setPaisDestinatario(String paisDestinatario) {
		this.paisDestinatario = paisDestinatario;
	}

	public Set getDetalleses() {
		return this.detalleses;
	}

	public void setDetalleses(Set detalleses) {
		this.detalleses = detalleses;
	}

}
