package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer id;
	private Categorias categorias;
	private Proveedores proveedores;
	private String producto;
	private String cantidadPorUnidad;
	private BigDecimal precioUnidad;
	private Short unidadesExistencia;
	private Short unidadesPedido;
	private Integer nivelNuevoPedido;
	private boolean suspendido;
	private String notas;
	private BigDecimal iva;
	private Set detalleses = new HashSet(0);

	public Productos() {
	}

	public Productos(String producto, boolean suspendido, BigDecimal iva) {
		this.producto = producto;
		this.suspendido = suspendido;
		this.iva = iva;
	}

	public Productos(Categorias categorias, Proveedores proveedores, String producto, String cantidadPorUnidad,
			BigDecimal precioUnidad, Short unidadesExistencia, Short unidadesPedido, Integer nivelNuevoPedido,
			boolean suspendido, String notas, BigDecimal iva, Set detalleses) {
		this.categorias = categorias;
		this.proveedores = proveedores;
		this.producto = producto;
		this.cantidadPorUnidad = cantidadPorUnidad;
		this.precioUnidad = precioUnidad;
		this.unidadesExistencia = unidadesExistencia;
		this.unidadesPedido = unidadesPedido;
		this.nivelNuevoPedido = nivelNuevoPedido;
		this.suspendido = suspendido;
		this.notas = notas;
		this.iva = iva;
		this.detalleses = detalleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public String getCantidadPorUnidad() {
		return this.cantidadPorUnidad;
	}

	public void setCantidadPorUnidad(String cantidadPorUnidad) {
		this.cantidadPorUnidad = cantidadPorUnidad;
	}

	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	public Short getUnidadesExistencia() {
		return this.unidadesExistencia;
	}

	public void setUnidadesExistencia(Short unidadesExistencia) {
		this.unidadesExistencia = unidadesExistencia;
	}

	public Short getUnidadesPedido() {
		return this.unidadesPedido;
	}

	public void setUnidadesPedido(Short unidadesPedido) {
		this.unidadesPedido = unidadesPedido;
	}

	public Integer getNivelNuevoPedido() {
		return this.nivelNuevoPedido;
	}

	public void setNivelNuevoPedido(Integer nivelNuevoPedido) {
		this.nivelNuevoPedido = nivelNuevoPedido;
	}

	public boolean isSuspendido() {
		return this.suspendido;
	}

	public void setSuspendido(boolean suspendido) {
		this.suspendido = suspendido;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	public Set getDetalleses() {
		return this.detalleses;
	}

	public void setDetalleses(Set detalleses) {
		this.detalleses = detalleses;
	}

}
