package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TotalesId generated by hbm2java
 */
public class TotalesId implements java.io.Serializable {

	private int id;
	private Date fechaPedido;
	private int clienteId;
	private Integer empleadoId;
	private Integer envioId;
	private BigDecimal cargo;
	private Double importe;
	private Double total;

	public TotalesId() {
	}

	public TotalesId(int id, int clienteId) {
		this.id = id;
		this.clienteId = clienteId;
	}

	public TotalesId(int id, Date fechaPedido, int clienteId, Integer empleadoId, Integer envioId, BigDecimal cargo,
			Double importe, Double total) {
		this.id = id;
		this.fechaPedido = fechaPedido;
		this.clienteId = clienteId;
		this.empleadoId = empleadoId;
		this.envioId = envioId;
		this.cargo = cargo;
		this.importe = importe;
		this.total = total;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	public Integer getEmpleadoId() {
		return this.empleadoId;
	}

	public void setEmpleadoId(Integer empleadoId) {
		this.empleadoId = empleadoId;
	}

	public Integer getEnvioId() {
		return this.envioId;
	}

	public void setEnvioId(Integer envioId) {
		this.envioId = envioId;
	}

	public BigDecimal getCargo() {
		return this.cargo;
	}

	public void setCargo(BigDecimal cargo) {
		this.cargo = cargo;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TotalesId))
			return false;
		TotalesId castOther = (TotalesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getFechaPedido() == castOther.getFechaPedido())
						|| (this.getFechaPedido() != null && castOther.getFechaPedido() != null
								&& this.getFechaPedido().equals(castOther.getFechaPedido())))
				&& (this.getClienteId() == castOther.getClienteId())
				&& ((this.getEmpleadoId() == castOther.getEmpleadoId()) || (this.getEmpleadoId() != null
						&& castOther.getEmpleadoId() != null && this.getEmpleadoId().equals(castOther.getEmpleadoId())))
				&& ((this.getEnvioId() == castOther.getEnvioId()) || (this.getEnvioId() != null
						&& castOther.getEnvioId() != null && this.getEnvioId().equals(castOther.getEnvioId())))
				&& ((this.getCargo() == castOther.getCargo()) || (this.getCargo() != null
						&& castOther.getCargo() != null && this.getCargo().equals(castOther.getCargo())))
				&& ((this.getImporte() == castOther.getImporte()) || (this.getImporte() != null
						&& castOther.getImporte() != null && this.getImporte().equals(castOther.getImporte())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getFechaPedido() == null ? 0 : this.getFechaPedido().hashCode());
		result = 37 * result + this.getClienteId();
		result = 37 * result + (getEmpleadoId() == null ? 0 : this.getEmpleadoId().hashCode());
		result = 37 * result + (getEnvioId() == null ? 0 : this.getEnvioId().hashCode());
		result = 37 * result + (getCargo() == null ? 0 : this.getCargo().hashCode());
		result = 37 * result + (getImporte() == null ? 0 : this.getImporte().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		return result;
	}

}
