package modelo_neptuno;
// Generated 20 ene. 2021 12:08:17 by Hibernate Tools 5.4.21.Final

/**
 * Totales generated by hbm2java
 */
public class Totales implements java.io.Serializable {

	private TotalesId id;

	public Totales() {
	}

	public Totales(TotalesId id) {
		this.id = id;
	}

	public TotalesId getId() {
		return this.id;
	}

	public void setId(TotalesId id) {
		this.id = id;
	}

}
